// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMM38nkdiSSGvEHnQDHmn7xozsVFmhAA',
    appId: '1:743244419249:web:83876c7b08b30f7103d290',
    messagingSenderId: '743244419249',
    projectId: 'login-fe73f',
    authDomain: 'login-fe73f.firebaseapp.com',
    databaseURL: 'https://login-fe73f-default-rtdb.firebaseio.com',
    storageBucket: 'login-fe73f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNsmdvVw6y_249rbU4kaQHdh_YgMlmPc',
    appId: '1:743244419249:android:f0624106a6b3b06903d290',
    messagingSenderId: '743244419249',
    projectId: 'login-fe73f',
    databaseURL: 'https://login-fe73f-default-rtdb.firebaseio.com',
    storageBucket: 'login-fe73f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUF-GoRzCQvjy4baorECmk7WMyWE0aW7g',
    appId: '1:743244419249:ios:a98e0604491d309103d290',
    messagingSenderId: '743244419249',
    projectId: 'login-fe73f',
    databaseURL: 'https://login-fe73f-default-rtdb.firebaseio.com',
    storageBucket: 'login-fe73f.firebasestorage.app',
    iosClientId: '743244419249-uve1j8jj4ka8old7esaorjoonk9v59l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.policeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUF-GoRzCQvjy4baorECmk7WMyWE0aW7g',
    appId: '1:743244419249:ios:a98e0604491d309103d290',
    messagingSenderId: '743244419249',
    projectId: 'login-fe73f',
    databaseURL: 'https://login-fe73f-default-rtdb.firebaseio.com',
    storageBucket: 'login-fe73f.firebasestorage.app',
    iosClientId: '743244419249-uve1j8jj4ka8old7esaorjoonk9v59l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.policeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPMM38nkdiSSGvEHnQDHmn7xozsVFmhAA',
    appId: '1:743244419249:web:33298618bebbe9e403d290',
    messagingSenderId: '743244419249',
    projectId: 'login-fe73f',
    authDomain: 'login-fe73f.firebaseapp.com',
    databaseURL: 'https://login-fe73f-default-rtdb.firebaseio.com',
    storageBucket: 'login-fe73f.firebasestorage.app',
  );

}